apiVersion: V1
kind: ReplecationController
metadata:
  name:myonlineapp-rc
spec:
  replicas: 3
  selector:
    app: mynginx
    version: 2.6.1
  template:
    metaddata:
      labels:
        app: mynginx
        version: 2.6.1
      spec:
         containers:
         - name: myonllineapp-container
           image: nginx
           ports: 
           - containerPort: 8080
